const {chromium}=require('/Users/macstudio/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',headless:true,args:['--no-first-run','--disable-sync']});
for(const [name,width,height]of [['iphone',390,844],['android',412,915],['desktop',1280,900]]){const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8139');await page.waitForFunction(()=>window.lastAssessment?.max);assert.equal(await page.locator('html').getAttribute('lang'),'en');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`aw139-category-a/research/${name}.png`,fullPage:true});
await page.locator('#available').fill('20');assert.equal(await page.locator('#distance-margin').evaluate(el=>getComputedStyle(el).color),'rgb(180, 35, 24)');
await page.locator('#mode').selectOption('training');assert.match(await page.locator('#status').textContent(),/PART L/);assert.equal(await page.locator('#distance').textContent(),'—');assert.equal(await page.locator('#margin').evaluate(el=>getComputedStyle(el).color),'rgb(180, 35, 24)');
await page.getByRole('button',{name:'View WAT source'}).click();await page.waitForFunction(()=>{const i=document.getElementById('chart-image');return i.complete&&i.naturalWidth>0;});await page.getByRole('button',{name:'Close',exact:true}).click();
await page.locator('#profile').selectOption('offshore');assert.match(await page.locator('#status').textContent(),/NOT COVERED/);assert.equal(await page.locator('#max').textContent(),'—');
await page.locator('#mode').selectOption('standard');await page.locator('#operation').selectOption('landing');await page.locator('#profile').selectOption('clearLanding');await page.locator('#pa').fill('6000');await page.locator('#oat').fill('12');assert.equal(await page.locator('#distance').textContent(),'439');
await page.locator('#weight').fill('');assert.equal(await page.locator('#max').textContent(),'—');assert.equal(await page.locator('#summary-margin').textContent(),'—');
assert.deepEqual(errors,[]);await context.close();console.log(name,'responsive, mode separation, source viewer and red margins passed');}
await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
