(()=>{'use strict';
const $=id=>document.getElementById(id), profiles=AW139.profiles;
const state={mode:'standard',weight:6000,oat:30,pa:0,config:'0',operation:'takeoff',profile:'confined',available:300,heater:'off',height:100,manoeuvre:'CTO'};
const fields=$('fields');
function row(label,id,control,cls=''){const r=document.createElement('div');r.className='row '+cls;const l=document.createElement(control?'label':'span');l.textContent=label;l.className='label';if(control)l.htmlFor=id;r.append(l);const el=control||document.createElement('output');el.id=id;r.append(el);fields.append(r);return el;}
function input(label,id,value,step,min,max){const el=document.createElement('input');el.type='number';el.inputMode='decimal';el.step=step;el.value=value;if(min!==undefined)el.min=min;if(max!==undefined)el.max=max;row(label,id,el);el.addEventListener('input',()=>{state[id]=el.value.trim()===''?NaN:Number(el.value);update();});}
function select(label,id,options,cls=''){const el=document.createElement('select');for(const [v,t]of options)el.add(new Option(t,v));el.value=state[id];row(label,id,el,cls);el.addEventListener('change',()=>{state[id]=el.value;if(id==='operation')rebuildProfile();if(id==='profile')rebuildManoeuvre();update();});return el;}
input('TOW / LW [kg]','weight',state.weight,.1,0,6800);input('Outside Air Temperature [°C]','oat',state.oat,.1,-40,50);input('Pressure Altitude [ft]','pa',state.pa,1,-1000,14000);
select('Intake / configuration','config',[['0','Clean intake'],['1','EAPS installed · OFF'],['2','EAPS installed · ON'],['3','IBF installed']],'profile');
select('Operation','operation',[['takeoff','Takeoff'],['landing','Landing']]);select('Category A Profile','profile',[],'profile');
input('Available Distance [m]','available',state.available,.1,0);
select('Heater / ECS heat','heater',[['off','OFF'],['on','ON / heat selected']]);
row('Actual PA used [ft]','actual-pa');row('Actual OAT used [°C]','actual-oat');select('Distance manoeuvre','manoeuvre',[]);
row('Interpolated Max Weight [kg]','max',null,'metric');row('Weight margin [kg]','margin',null,'metric');input('TDP / LDP height [ft]','height',state.height,1);
row('Required Distance [m]','distance',null,'metric');row('Distance margin [m]','distance-margin',null,'metric');row('Weight Feasibility — WAT','wat-state',null,'status');row('Distance Feasibility','distance-state',null,'status');row('Data / applicability status','status',null,'status');row('Numerical comparison result','comparison',null,'status');row('Full Category A assessment','full',null,'status');
const mn={CTO:'CTO',RTO:'RTO',LD:'LD',BL:'BL'};
function rebuildProfile(){const options=Object.entries(profiles).filter(([k,p])=>p.operation===state.operation);const el=$('profile');el.replaceChildren(...options.map(([k,p])=>new Option(p.label+' · Part '+p.part,k)));if(!options.some(([k])=>k===state.profile))state.profile=options[0][0];el.value=state.profile;rebuildManoeuvre();}
function rebuildManoeuvre(){const p=profiles[state.profile];$('manoeuvre').replaceChildren(...p.manoeuvres.map(k=>new Option(mn[k],k)));if(!p.manoeuvres.includes(state.manoeuvre))state.manoeuvre=p.manoeuvres[0];$('manoeuvre').value=state.manoeuvre;state.height=p.height[0];$('height').value=state.height;$('height').min=p.height[0];$('height').max=p.height[1];$('height').readOnly=p.height[0]===p.height[1];document.querySelector('label[for="height"]').textContent=(p.operation==='takeoff'?'TDP':'LDP')+' height [ft '+(p.operation==='landing'?'ALS':state.profile==='short'||state.profile==='clear'?'AGL':'ATS')+']';}
function val(id,v,digits=0){const el=$(id);el.textContent=Number.isFinite(v)?v.toLocaleString('en-GB',{minimumFractionDigits:digits,maximumFractionDigits:digits}):'—';el.classList.toggle('negative',Number.isFinite(v)&&v<0);}
function status(id,text){const el=$(id);el.textContent=text;el.className=/ABOVE|EXCEEDED|INSUFFICIENT/.test(text)?'bad':/WITHIN|SUFFICIENT|SATISFIED/.test(text)?'good':'warn';}
function sourceLabel(n){const s=AW139_SOURCES.find(c=>c.page===n);return s?`${s.label} · PDF ${n}`:`PDF page ${n}`;}
function sourceButton(n,title){const b=document.createElement('button');b.type='button';b.textContent=title;b.addEventListener('click',()=>view(n));return b;}
function update(){const r=AW139.assess(state);document.body.classList.toggle('mode-training',state.mode==='training');val('actual-pa',state.pa,1);val('actual-oat',state.oat,1);val('max',r.max);val('margin',r.margin,1);val('distance',r.distance);val('distance-margin',r.distanceMargin,1);val('summary-max',r.max);val('summary-margin',r.margin,1);status('wat-state',r.watState);status('summary-state',r.watState);status('distance-state',r.distanceState);status('status',r.status);status('comparison',r.comparison);status('full',r.full);$('summary-source').textContent=(state.mode==='training'?'Training':'Standard')+' · '+(r.watFigure||'—');$('reference-wat').textContent=r.watPage?sourceLabel(r.watPage):'—';$('reference-distance').textContent=r.distancePages.length?r.distancePages.map(sourceLabel).join(' + '):'Not assessable';$('reference-note').textContent=r.note||r.status;$('reference-conditions').textContent=r.conditions;$('source-buttons').replaceChildren();if(r.watPage)$('source-buttons').append(sourceButton(r.watPage,'View WAT source'));for(const n of r.distancePages)$('source-buttons').append(sourceButton(n,sourceLabel(n)));$('source-buttons').append(sourceButton(profiles[state.profile].page,'Profile / height limits'));if(state.mode==='training')$('source-buttons').append(sourceButton(512,'Part L applicability'),sourceButton(513,'Training limitations'),sourceButton(517,'Training performance note'));window.lastAssessment=r;}
$('mode').addEventListener('change',()=>{state.mode=$('mode').value;update();});
function view(n){$('chart-title').textContent=sourceLabel(n);$('chart-body').classList.remove('zoom');$('chart-image').src='./charts/p'+n+'.webp';$('chart-image').alt=`Supplied AW139 RFM, ${sourceLabel(n)}`;$('chart-dialog').showModal();$('chart-body').scrollTo(0,0);}
$('close-chart').onclick=()=>$('chart-dialog').close();$('zoom-chart').onclick=()=>$('chart-body').classList.toggle('zoom');$('chart-dialog').addEventListener('click',e=>{if(e.target===$('chart-dialog'))$('chart-dialog').close();});
const names={General:'General limitations',A:'Vertical Takeoff',B:'Short Field Takeoff',C:'Back-Up Takeoff',D:'Confined Area Takeoff',E:'Offshore Takeoff',F:'Clear Area Takeoff',G:'Heliport Landing',H:'Confined Area Landing',I:'Offshore Landing',J:'Clear Area Landing',K:'Common Performance',L:'Training Procedures'};
for(const [part,name]of Object.entries(names))$('source-part').add(new Option(`${part==='General'?'General':'Part '+part} · ${name}`,part));
function library(){const list=AW139_SOURCES.filter(s=>s.part===$('source-part').value);$('source-page').replaceChildren(...list.map(s=>new Option(sourceLabel(s.page),s.page)));}
$('source-part').onchange=library;$('open-source').onclick=()=>view(Number($('source-page').value));library();rebuildProfile();update();
})();
